spring.application.name=mybatis

# Đường dẫn kết nối đến database tên là "testdb" trong bộ nhớ
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Bật chế độ Console để lát nữa chúng ta có thể xem dữ liệu trên trình duyệt
spring.h2.console.enabled=true

# config mapper class path
mybatis.mapper-locations=classpath:mapper/*.xml

# config type aliases
mybatis.type-aliases-package=com.learning.mybatis.entity

