spring.application.name=mybatis

# ???ng d?n k?t n?i ??n database tên là "testdb" trong b? nh?
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# B?t ch? ?? Console ?? lát n?a chúng ta có th? xem d? li?u trên trình duy?t
spring.h2.console.enabled=true
